trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: npm i yarn -g;
    yarn install;
    yarn build;
  displayName: 'Build'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
