trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: npm i yarn -g;        
  displayName: 'Install Yarn'
  workingDirectory: 'website'

- script: yarn install    
  displayName: 'Install App'
  workingDirectory: 'website'

- script: yarn install    
  displayName: 'PreBuild'
  workingDirectory: 'website'

- script: yarn build
  displayName: 'Build'
  workingDirectory: 'website'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'website/public'
    ArtifactName: 'drop'
    publishLocation: 'Container'
